# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "rc" ]
  
jobs:
  get-version:
      name: Read version
      runs-on: ubuntu-latest
      steps:
      - run: ls
      - uses: kzrnm/get-net-sdk-project-versions-action@v1.1.2
        id: get-version
        with:
          proj-path: src/src.csproj
      - run: echo "${{steps.get-version.outputs.version}}"
      - name: Create timestamp
        id: timestamp
        run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT
      - name: Create tag and GitHub release
        id: create_tag_and_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.get-version.outputs.version }}.${{ steps.timestamp.outputs.timestamp }}-rc
          release_name: v${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false  
            
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup .NET SDK
#        uses: actions/setup-dotnet@v3
#      - name: Install dependencies
#        run: dotnet restore
#      - name: Build
#        if: 
#        run: dotnet build --configuration Release --no-restore
#      - name: Create the package
#        run: dotnet pack --configuration Release <my project>
